### PR TITLE
fix: allow set-hardening-level option usage

### LINKED ISSUE #230: hardening.sh --set-hardening-level does not work
Debian 12, up to date.

When I try to run:

./bin/hardening.sh --set-hardening-level 1

It simply gives me the help info, as if I have entered the command in incorrectly. Other switches work, such as --audit-all-enable-passed, --audit, --apply

I have even spun up a new VM from scratch, and still get this issue. I am unable to run the  --set-hardening-level switch.

### PR DESCRIPTION
**Pull request by ThibaultDewailly**
Was broken since 2020, fixes #230

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-bullseye-amd64#490.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-stretch-amd64#490.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-buster-amd64#490.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-buster-amd64#491.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-bookworm-amd64#490.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-bullseye-amd64#492.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-stretch-amd64#492.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-buster-amd64#493.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-buster-amd64#492.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-bullseye-amd64#493.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-bookworm-amd64#492.0 ✔ 
* 
  * Build ✔

**Comment by ovh-cds** [comment]
CDS Report build-bookworm-amd64#493.0 ✔ 
* 
  * Build ✔

**Review by tdenof — APPROVED** [review]

**Pull request merged**
